#include "meta.hpp"
#include <nlohmann/json.hpp>
#include <fstream>

using namespace cheats::meta;

// structures below were generated automatically
// thank god for html agility pack

std::unordered_map<std::string_view, std::string> cheats::meta::item_translation_table {
    // powers/items
    { "Item_Slasher_Frenzy", "Frenzy" },

    // addons
    { "Addon_Spark_IridescentGeneral", "Iridescent King" },
    { "Addon_Spark_JadeCharm", "Iridescent Queen" },

    // killer perks
    { "ZanshinTactics", "Zanshin Tactics" },
    { "Unnerving_Presence", "Unnerving Presence" },
    { "SpiritFury", "Spirit Fury" },
    { "Sloppy_Butcher", "Sloppy Butcher" },
    { "OverwhelmingPresence", "Overwhelming Presence" },
    { "InTheDark", "Knock Out" },
    { "Iron_Grasp", "Iron Grasp" },
    { "FireUp", "Fire Up" },
    { "HangmansTrick", "Hangman's Trick" },
    { "Hex_Thrill_Of_The_Hunt", "Hex: Thrill of the Hunt" },
    { "ImAllEars", " I'm All Ears" },
    { "CorruptIntervention", "Corrupt Intervention" },
    { "BeastOfPrey", "Beast of Prey" },
    { "ThrillingTremors", "Thrilling Tremors" },
    { "TerritorialImperative", "Territorial Imperative" },
    { "Spies_From_The_Shadows", "Spies from the shadows" },
    { "Save_The_Best_For_Last", "Save the Best for Last" },
    { "RememberMe", "Remember Me" },
    { "pop_goes_the_weasel", "Pop Goes The Weasel" },
    { "Play_With_Your_Food", "Play With Your Food" },
    { "GeneratorOvercharge", "Overcharge" },
    { "Monstrous_Shrine", "Monstrous Shrine" },
    { "MadGrit", "Mad Grit" },
    { "MakeYourChoice", "Make Your Choice" },
    { "MonitorAndAbuse", "Monitor and Abuse" },
    { "IronMaiden", "Iron Maiden" },
    { "InfectiousFright", "Infectious Fright" },
    { "Hex_The_Third_Seal", "Hex: The Third Seal" },
    { "Hex_HauntedGround", "Hex: Haunted Ground" },
    { "Hex_HuntressLullaby", "Hex: Huntress Lullaby" },
    { "No_One_Escapes_Death", "Hex: No One Escapes Death" },
    { "Hex_Ruin", "Hex: Ruin" },
    { "Hex_Devour_Hope", "Hex: Devour Hope" },
    { "FurtiveChase", "Furtive Chase" },
    { "FranklinsLoss", "Franklin's Demise" },
    { "Dying_Light", "Dying Light" },
    { "DarkDevotion", "Dark Devotion" },
    { "CruelConfinement", "Cruel Limits" },
    { "Brutal_Strength", "Brutal Strength" },
    { "BloodWarden", "Bloodwarden" },
    { "BloodEcho", "Blood Echo" },
    { "Bitter_Murmur", "Bitter Murmur" },
    { "NurseCalling", "Nurse's Calling" },
    { "BBQAndChilli", "Barbecue and Chilli" },

    // survivors items and addons
    { "Item_Camper_CommodiousToolbox", "Commodious Toolbox" },
    { "Item_Camper_MechanicsToolbox", "Mechanic's Toolbox" },
    { "Item_Camper_AlexsToolbox", "Alex's Toolbox" },
    { "Item_Camper_EngineerToolbox", "Engineer's Toolbox" },
    { "Item_Camper_Toolbox", "Toolbox" },
    { "Item_Camper_WornoutToolbox", "Wornout Toolbox" },
    { "ADDON_toolbox_springclamp", "Spring Clamp" },
    { "ADDON_toolbox_socketswivels", "Socket Swivels" },
    { "ADDON_toolbox_cuttingwire", "Cutting Wire" },
    { "Addon_Toolbox_001", "Scraps" },
    { "Addon_Toolbox_002", "Wire Spool" },
    { "Addon_Toolbox_003", "Clean Rag" },
    { "Addon_Toolbox_004", "Protective Gloves" },
    { "Addon_Toolbox_005", "Hacksaw" },
    { "Addon_Toolbox_006", "Grip Wrench" },
    { "Item_Camper_MedKit", "Camping Aid Kit" },
    { "Item_Camper_MedKit02", "First Aid Kit" },
    { "Item_Camper_MedKit03", "Emergency Med-kit" },
    { "Item_Camper_MedKit04", "Ranger Med-kit" },
    { "Addon_Medkit_001", "Bandages" },
    { "Addon_Medkit_002", "Gel Dressings" },
    { "Addon_Medkit_003", "Medical Scissors" },
    { "Addon_Medkit_004", "Butterfly Tape" },
    { "Addon_Medkit_005", "Sponge" },
    { "Addon_Medkit_006", "Rubber Gloves" },
    { "ADDON_medkit_selfadherentwrap", "Self adherent wrap" },
    { "ADDON_medkit_needleandthread", "Needle and Thread" },
    { "ADDON_medkit_gauzeroll", "Gauze Roll" },
    { "ADDON_medkit_surgicalsuture", "Surgical Suture" },
    { "ADDON_medkit_abdominaldressing", "Abdominal Dressing" },
    { "Addon_Medkit_007", "Styptic Agent" },
    { "Addon_Medkit_008", "Anti-Hemorrhagic Syringe" },
    { "Item_Camper_Flashlight03", "Utility Flashlight" },
    { "Item_Camper_Flashlight02", "Sport Flashlight" },
    { "Item_Camper_Flashlight", "Flashlight" },
    { "Addon_Flashlight_001", "Battery" },
    { "Addon_Flashlight_002", "Heavy Duty Battery" },
    { "Addon_Flashlight_003", "Focus Lens" },
    { "Addon_Flashlight_004", "Wide Lens" },
    { "Addon_Flashlight_005", "Power Bulb" },
    { "Addon_Flashlight_006", "Tir Optic" },
    { "Addon_Flashlight_007", "Low Amp Filament" },
    { "Addon_Flashlight_008", "Leather Grip" },
    { "ADDON_flashlight_rubbergrip", "Rubber Grip" },
    { "ADDON_flashlight_lonflifebattery", "Long Life Battery" },
    { "ADDON_flashlight_intensehalogen", "Intense Halogen" },
    { "ADDON_flashlight_highendsapphire", "High-End Sapphire Lens" },
    { "ADDON_flashlight_oddbulb", "Odd Bulb" },
    { "Item_Camper_BrokenKey", "Broken Key" },
    { "Item_Camper_Key", "Skeleton Key" },
    { "Item_Camper_DullKey", "Dull Key" },
    { "Addon_Key_001", "Prayer Rope" },
    { "Addon_Key_002", "Prayer Beads" },
    { "Addon_Key_003", "Eroded Token" },
    { "Addon_Key_004", "Gold Token" },
    { "Addon_Key_005", "Blood Amber" },
    { "Addon_Key_006", "Milky Glass" },
    { "Addon_Key_007", "Weaved Ring" },
    { "Addon_Key_008", "Scratched Pearl" },
    { "Addon_Key_WeddingRing", "Wedding Ring" },
    { "Item_Camper_Firecracker_Chinese", "Chinese Firecracker" },
    { "Item_Camper_RainbowMap", "Rainbow Map" },
    { "Item_Camper_BeigeMap", "Map" },

    // survivor perks with weird names (or names that aren't easily translated into normal case)
    { "SelfSufficient", "Unbreakable" },
    { "QuickQuiet", "Quick and Quiet" },

    // offerings with weird names
    { "KenyaThemeOffering", "Damaged Photo" },
    { "GranmasCookbook", "Grandma's Cookbook" },
    { "AzarovKey", "Azarov's Key" },
    { "VigosJarOfSaltyLips", "Vigo's Jar of Salty Lips" },
    { "ShroudofBinding", "Shroud of Binding" },
    { "ShroudofUnion", "Shroud of Union" },
    { "JapaneseCountrySide", "Yamaoka Family Crest" },
    { "QatarThemeOffering", "Hawkins National Laboratory I.D." },

    // killer addons
    { "Addon_Demogorgon_LerproseLichen", "Leprose Lichen" },
    { "ADDON_trap_DiamondStone", "Iridescent Stone" },
    { "Addon_Beartrap_012", "Fastening Tools" },
    { "Addon_Beartrap_001", "Honing Stone" },
    { "Addon_Beartrap_011", "Secondary Coil" },
    { "Addon_Beartrap_009", "Setting Tools" },
    { "Addon_Beartrap_006", "Tar Bottle" },
    { "Addon_Beartrap_004", "Wax Brick" },
    { "Addon_Beartrap_008", "4-Coil Spring Kit" },
    { "Addon_Beartrap_005", "LogWood Dye" },
    { "Addon_Beartrap_002", "Serrated Jaws" },
    { "Addon_Beartrap_003", "Trapper Bag" },
    { "Addon_Beartrap_007", "Strong Coil Spring" },
    { "Addon_Beartrap_010", "Trapper Gloves" },
    { "Addon_Chainsaw_009", "Begrimed Chain" },
    { "Addon_Chainsaw_010", "Rusted Chain" },
    { "Addon_Chainsaw_007", "Depth Gauge Rake" },
    { "Addon_Chainsaw_008", "Grisly Chain" },
    { "Addon_Chainsaw_002", "Long Guide Bar" },
    { "Addon_Chainsaw_004", "Primer Bulb" },
    { "Addon_Chainsaw_006", "Shop Lubricant" },
    { "Addon_Chainsaw_011", "Speed Limiter" },
    { "Addon_Chainsaw_001", "Spiked Boots" },
    { "Addon_Chainsaw_012", "Chainsaw File" },
    { "Addon_Chainsaw_003", "Spark Plug" },
    { "Addon_Chainsaw_005", "Vegetable Oil" },
    { "Addon_Blinker_005", "Torn BookMark" },
    { "Addon_Blinker_008", "Campbell's Last Breath" },
    { "Addon_Blinker_004", "Anxious Gasp" },
    { "Addon_Blinker_007", "Fragile Wheeze" },
    { "Addon_Blinker_010", "Bad Man KeepSake" },
    { "Addon_Blinker_012", "Catatonic Boy's Treasure" },
    { "Addon_Blinker_006", "Dark Cincture" },
    { "Addon_Blinker_003", "Pocket Watch" },
    { "Addon_Blinker_009", "Metal Spoon" },
    { "Addon_Blinker_001", "Plaid Flannel" },
    { "Addon_Blinker_002", "White Nit Comb" },
    { "Addon_Blinker_011", "Wooden Horse" },
    { "Addon_Bell_008", "All Seeing Blood" },
    { "ADDON_Bell_BlindSpirit", "Shadow Dance Blood" },
    { "Addon_Bell_006", "Swift Hunt Blood" },
    { "Addon_Bell_012", "Blink White" },
    { "ADDON_Bell_BlindBlood", "Shadow Dance White" },
    { "Addon_Bell_010", "WindStorm White" },
    { "Addon_Bell_004", "Blind Warrior" },
    { "Addon_Bell_011", "Blink Mud" },
    { "Addon_Bell_005", "Swift Hunt Mud" },
    { "Addon_Bell_009", "WindStorm Mud" },
    { "Addon_Bell_001", "Bone Clapper" },
    { "Addon_Bell_007", "The Beast" },
    { "Addon_Bell_002", "The Ghost" },
    { "Addon_Bell_003", "The Hound" },
    { "ADDON_Bell_AllseeingWhite", "The Serpent" },
    { "Addon_Spark_CalmMuYisNotes", "Calm Carter's Note" },
    { "Addon_Spark_DisciplineMuYisNotes", "Discipline Carter's Note" },
    { "Addon_Spark_OrderMuYisNotes", "Order Carter's Note" },
    { "Addon_Spark_RestraintMuYisNotes", "Restraint Carter's Note" },
    { "Addon_Spark_Obedience_MuYisNotes", "Obedience Carter's Note" },
    { "Addon_Spark_TigerFangCharm", "Interview Tape" },
    { "Addon_Spark_NanmuCatapult", "Maple Knight" },
    { "ADDON_Bell_BlindWhite", "Blind Warrior White" }
};

std::unordered_map<std::string, item_entry> cheats::meta::item_entries;

bool cheats::meta::init()
{
    std::ifstream ifs( "internal_wiki.json" );

    auto parsed = nlohmann::json::parse( ifs );

    auto raw_struct = parsed.get<std::vector<std::pair<std::string, std::tuple<std::string, std::string, int>>>>();
    for ( auto &[ item_id, s ] : raw_struct ) {
        auto &[ name, desc, rarity ] = s;
        item_entries[ item_id ] = item_entry { name, desc, static_cast<item_rarity>( rarity ) };
    }

    return true;
}
